name: Periodic health check

on:
  schedule:
    - cron: '8,38 * * * *'

jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL health check
        uses: Jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://fs-w11-pokedex.fly.dev/health
